{% set name = "policy_sentry" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/policy_sentry-{{ version }}.tar.gz
  sha256: 5c52cebebad26e2360393f34af523c1685541d67b0dfd721b0779dbe9e327f1a

build:
  number: 0
  noarch: python
  entry_points:
    - policy_sentry=policy_sentry.bin.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - beautifulsoup4
    - click
    - python >=3.6
    - pyyaml
    - requests
    - schema
    - orjson

test:
  imports:
    - policy_sentry
    - policy_sentry.analysis
  commands:
    - pip check
    - policy_sentry --help
  requires:
    - pip

about:
  home: https://github.com/salesforce/policy_sentry
  summary: Generate locked-down AWS IAM Policies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ForgottenProgramme
    - nick-harmening
